on:
  pull_request:
  push:
defaults:
  run:
    shell: bash    
jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container:
      image: ghcr.io/berserkerrider/ubuntu20-ros2:v1.1
      credentials:
         username: ${{ secrets.GIT_USER }}
         password: ${{ secrets.GIT_TOKEN }}
     # env:
     #  NODE_ENV: development
      ports:
        - 80
      volumes:
        - ${{github.workspace}}:/home/ros2/src/
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: |
             cd /home/ros2 && \
             find -name "setup.bash"
             #source /opt/ros2/galactic/setup.bash && \ 
             #colcon build --packages-up-to demo_nodes_cpp
