name: GitHub Actions CI
run-name: ${{ github.actor }} is run GitHub Actions 🚀
on: [push]
defaults:
  run:
    shell: bash
jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}
      - name: Install dependence
        run: |
          sudo apt install -y qemu-user-static binfmt-support
      - name: Download code
        uses: actions/checkout@v3
      - name: Build and code test
        run: |
             docker pull ghcr.io/berserkerrider/build_image:v1
             docker run -i -v /home/runner/work/buoyancy/buoyancy:/home/ros2/src ghcr.io/berserkerrider/build_image:v1 bash -c \
             "cd /home/ros2 && source /opt/ros2/galactic/setup.bash
             #  && colcon build --packages-select cpp_pubsub \
             # && colcon test --event-handlers console_cohesion+ --return-code-on-test-failure --packages-select cpp_pubsub"
             # colcon build test
