on:
  pull_request:
  push:
      
jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container:
      image: ghcr.io/berserkerrider/ubuntu20-ros2:v1
      credentials:
         username: ${{ secrets.GIT_USER }}
         password: ${{ secrets.GIT_TOKEN }}
     # env:
     #  NODE_ENV: development
      ports:
        - 80
      volumes:
        - /home/runner/work/TestReo:/home/TestReo
    steps:
      - run: |
             ls
