on:
  pull_request:
  push:
defaults:
  run:
    shell: bash    
jobs:
  container-job:
    # Containers must run in Linux based operating systems
    runs-on: ubuntu-latest
    # Docker Hub image that `container-job` executes in
    container:
      image: ghcr.io/berserkerrider/ubuntu20-ros2:v1
      credentials:
         username: ${{ secrets.GIT_USER }}
         password: ${{ secrets.GIT_TOKEN }}
     # env:
     #  NODE_ENV: development
      ports:
        - 80
      volumes:
        - ${{GITHUB_WORKSPACE}}:/home/ros2/src/
    steps:
      - run: |
             echo $GITHUB_WORKSPACE && \
             cd /home/ros2/src
      - name: Checkout
        uses: actions/checkout@v3
        with: 
              path: '/home/ros2/src'
      - run: |
             cd /home/ros2 && \
             colcon build --packages-select demo_nodes_cpp
